language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
before_install:
  - cpanm --notest --quiet Dist::Zilla
  - dzil authordeps --notest --quiet | cpanm
  - cpanm --notest --quiet Pod::Coverage::TrustPod
  - perl -c ./apigen.pl
install:
  - dzil listdeps --notest --quiet | cpanm
script:
  - dzil test --release --verbose
